-- Phase 4, minimized read-only contract v2. Apply ONCE; not applied remotely.
-- No tables, policies, triggers, backfill or catalog/workflow writes.
begin;

create function public.admin_catalog_data_origin(p_club_id uuid)
returns jsonb language plpgsql stable security definer set search_path=pg_catalog as $$
declare result jsonb;
begin
  perform public.admin_catalog_require_admin();
  if not exists(select 1 from public.clubs where id=p_club_id) then
    raise exception 'Existing club required' using errcode='22023';
  end if;
  -- Snapshot/payload comparisons stay PRIVATE in these CTEs. Only allowlisted
  -- scalars, typed matrix cells and synthetic diagnostics reach the response.
  -- Fixed column lists never export new columns added by a future migration.
  with course_sources as (
    select c.id,c.source_payload,jsonb_build_object('id',c.id,'club_id',c.club_id,'name',c.name,'holes_count',c.holes_count,'total_par',c.total_par,'display_order',c.display_order,'is_active',c.is_active,'created_at',c.created_at,'updated_at',c.updated_at,'source_system',c.source_system,'source_external_id',c.source_external_id) course_value,
      (select count(*) from public.route_holes h where h.route_id=c.id) hole_count,
      (select coalesce(jsonb_agg(jsonb_build_object('id',h.id,'route_id',h.route_id,'physical_hole_number',h.physical_hole_number,'par',h.par,'stroke_index',h.stroke_index,'display_label',h.display_label,'created_at',h.created_at)),'[]') from public.route_holes h where h.route_id=c.id) hole_values
    from public.course_routes c where c.club_id=p_club_id
  ), combination_sources as (
    select c.id,c.source_payload,jsonb_build_object('id',c.id,'club_id',c.club_id,'name',c.name,'front_route_id',c.front_route_id,'back_route_id',c.back_route_id,'holes_count',c.holes_count,'total_par',c.total_par,'is_active',c.is_active,'created_at',c.created_at,'updated_at',c.updated_at,'source_system',c.source_system,'source_external_id',c.source_external_id) combination_value,
      (select count(*) from public.route_combination_holes h where h.route_combination_id=c.id) hole_count,
      (select coalesce(jsonb_agg(jsonb_build_object('id',h.id,'route_combination_id',h.route_combination_id,'round_hole_number',h.round_hole_number,'route_id',h.route_id,'route_position',h.route_position,'physical_hole_number',h.physical_hole_number,'par',h.par,'stroke_index',h.stroke_index,'source_stroke_index',h.source_stroke_index,'display_label',h.display_label,'created_at',h.created_at)),'[]') from public.route_combination_holes h where h.route_combination_id=c.id) hole_values
    from public.route_combinations c where c.club_id=p_club_id
  ), eligible_drafts as (
    select d.* from public.admin_catalog_drafts d where d.workflow_status='draft' and ((d.entity_type='club' and d.live_entity_id=p_club_id)
      or (d.entity_type in ('course','route','route_holes_grid') and exists(select 1 from public.course_routes c where c.id=d.live_entity_id and c.club_id=p_club_id))
      or (d.entity_type in ('route_combination','combination_holes_grid') and exists(select 1 from public.route_combinations c where c.id=d.live_entity_id and c.club_id=p_club_id))
      or (d.entity_type='hole' and exists(select 1 from public.route_holes h join public.course_routes c on c.id=h.route_id where h.id=d.live_entity_id and c.club_id=p_club_id))
      or (d.entity_type='combination_hole' and exists(select 1 from public.route_combination_holes h join public.route_combinations c on c.id=h.route_combination_id where h.id=d.live_entity_id and c.club_id=p_club_id))
      or (d.entity_type='route_tee' and exists(select 1 from public.route_tees t join public.course_routes c on c.id=t.route_id where t.id=d.live_entity_id and c.club_id=p_club_id))
      or (d.entity_type='combination_tee' and exists(select 1 from public.combination_tees t join public.route_combinations c on c.id=t.route_combination_id where t.id=d.live_entity_id and c.club_id=p_club_id)))
  ), draft_values as (
    select d.*,
      case d.entity_type
      when 'club' then jsonb_build_object('name',d.snapshot->'name','city',d.snapshot->'city')
      when 'route' then jsonb_build_object('name',d.snapshot->'name','holes_count',d.snapshot->'holes_count','display_order',d.snapshot->'display_order','is_active',d.snapshot->'is_active')
      when 'route_combination' then jsonb_build_object('name',d.snapshot->'name','is_active',d.snapshot->'is_active')
      when 'route_tee' then jsonb_build_object('course_rating',d.snapshot->'course_rating','slope_rating',d.snapshot->'slope_rating','is_active',d.snapshot->'is_active')
      when 'route_holes_grid' then case when jsonb_typeof(d.snapshot->'holes')='array' then jsonb_build_object('holes',(select coalesce(jsonb_agg(jsonb_build_object('id',x->'id','physical_hole_number',x->'physical_hole_number','par',x->'par','stroke_index',x->'stroke_index') order by x->>'id'),'[]') from jsonb_array_elements(case when jsonb_typeof(d.snapshot->'holes')='array' then d.snapshot->'holes' else '[]'::jsonb end) x)) else null end
      when 'combination_holes_grid' then case when jsonb_typeof(d.snapshot->'holes')='array' then jsonb_build_object('holes',(select coalesce(jsonb_agg(jsonb_build_object('id',x->'id','round_hole_number',x->'round_hole_number','route_position',x->'route_position','physical_hole_number',x->'physical_hole_number','par',x->'par','stroke_index',x->'stroke_index') order by x->>'id'),'[]') from jsonb_array_elements(case when jsonb_typeof(d.snapshot->'holes')='array' then d.snapshot->'holes' else '[]'::jsonb end) x)) else null end
      else null end snapshot_value,
      case d.entity_type
      when 'club' then jsonb_build_object('name',d.base_snapshot->'name','city',d.base_snapshot->'city')
      when 'route' then jsonb_build_object('name',d.base_snapshot->'name','holes_count',d.base_snapshot->'holes_count','display_order',d.base_snapshot->'display_order','is_active',d.base_snapshot->'is_active')
      when 'route_combination' then jsonb_build_object('name',d.base_snapshot->'name','is_active',d.base_snapshot->'is_active')
      when 'route_tee' then jsonb_build_object('course_rating',d.base_snapshot->'course_rating','slope_rating',d.base_snapshot->'slope_rating','is_active',d.base_snapshot->'is_active')
      when 'route_holes_grid' then case when jsonb_typeof(d.base_snapshot->'holes')='array' then jsonb_build_object('holes',(select coalesce(jsonb_agg(jsonb_build_object('id',x->'id','physical_hole_number',x->'physical_hole_number','par',x->'par','stroke_index',x->'stroke_index') order by x->>'id'),'[]') from jsonb_array_elements(case when jsonb_typeof(d.base_snapshot->'holes')='array' then d.base_snapshot->'holes' else '[]'::jsonb end) x)) else null end
      when 'combination_holes_grid' then case when jsonb_typeof(d.base_snapshot->'holes')='array' then jsonb_build_object('holes',(select coalesce(jsonb_agg(jsonb_build_object('id',x->'id','round_hole_number',x->'round_hole_number','route_position',x->'route_position','physical_hole_number',x->'physical_hole_number','par',x->'par','stroke_index',x->'stroke_index') order by x->>'id'),'[]') from jsonb_array_elements(case when jsonb_typeof(d.base_snapshot->'holes')='array' then d.base_snapshot->'holes' else '[]'::jsonb end) x)) else null end
      else null end base_value,
      case d.entity_type
        when 'club' then (select jsonb_build_object('name',c.name,'city',c.city) from public.clubs c where c.id=d.live_entity_id and c.id=p_club_id)
        when 'route' then (select jsonb_build_object('name',c.name,'holes_count',c.holes_count,'display_order',c.display_order,'is_active',c.is_active) from public.course_routes c where c.id=d.live_entity_id and c.club_id=p_club_id)
        when 'route_combination' then (select jsonb_build_object('name',c.name,'is_active',c.is_active) from public.route_combinations c where c.id=d.live_entity_id and c.club_id=p_club_id)
        when 'route_tee' then (select jsonb_build_object('course_rating',t.course_rating,'slope_rating',t.slope_rating,'is_active',t.is_active) from public.route_tees t join public.course_routes c on c.id=t.route_id where t.id=d.live_entity_id and c.club_id=p_club_id)
        when 'route_holes_grid' then (select jsonb_build_object('holes',coalesce(jsonb_agg(jsonb_build_object('id',h.id,'physical_hole_number',h.physical_hole_number,'par',h.par,'stroke_index',h.stroke_index) order by h.id::text),'[]')) from public.route_holes h join public.course_routes c on c.id=h.route_id where h.route_id=d.live_entity_id and c.club_id=p_club_id)
        when 'combination_holes_grid' then (select jsonb_build_object('holes',coalesce(jsonb_agg(jsonb_build_object('id',h.id,'round_hole_number',h.round_hole_number,'route_position',h.route_position,'physical_hole_number',h.physical_hole_number,'par',h.par,'stroke_index',h.stroke_index) order by h.id::text),'[]')) from public.route_combination_holes h join public.route_combinations c on c.id=h.route_combination_id where h.route_combination_id=d.live_entity_id and c.club_id=p_club_id)
        else null end current_value,
      case when d.entity_type='club' then (select c.updated_at from public.clubs c where c.id=p_club_id)
        when d.entity_type in ('route','route_holes_grid') then (select c.updated_at from public.course_routes c where c.id=d.live_entity_id and c.club_id=p_club_id)
        when d.entity_type in ('route_combination','combination_holes_grid') then (select c.updated_at from public.route_combinations c where c.id=d.live_entity_id and c.club_id=p_club_id)
        when d.entity_type='route_tee' then (select t.updated_at from public.route_tees t join public.course_routes c on c.id=t.route_id where t.id=d.live_entity_id and c.club_id=p_club_id)
        else null end live_updated_at,
      (select v.version_id from public.admin_catalog_versions v where v.entity_type=d.entity_type and v.live_entity_id=d.live_entity_id order by v.version_number desc limit 1) latest_version_id
    from eligible_drafts d
  ) select jsonb_build_object(
    'contract_version',2,'read_only',true,'read_at',statement_timestamp(),'publication','not_assessed',
    'club',(select jsonb_build_object('id',c.id,'name',c.name) from public.clubs c where c.id=p_club_id),
    'structures',(select coalesce(jsonb_agg(jsonb_build_object('id',s.id,'club_id',s.club_id,'label',s.label,'classification',s.classification,'review_status',s.review_status,'revision',s.revision,'created_at',s.created_at,'updated_at',s.updated_at) order by s.id),'[]') from public.admin_catalog_physical_structures s where s.club_id=p_club_id),
    'physical_holes',(select coalesce(jsonb_agg(jsonb_build_object('id',h.id,'club_id',h.club_id,'structure_id',h.structure_id,'physical_number',h.physical_number,'base_par',h.base_par,'review_status',h.review_status,'revision',h.revision,'source_system',case when h.source_system in ('fig','gesgolf','stablr','other','official_club_site') then h.source_system else null end,'source_course_link_id',h.source_course_link_id,'source_route_hole_id',h.source_route_hole_id,'source_position',h.source_position,'created_at',h.created_at,'updated_at',h.updated_at) order by h.source_course_link_id,h.physical_number,h.id),'[]') from public.admin_catalog_physical_holes h where h.club_id=p_club_id),
    'physical_links',(select coalesce(jsonb_agg(jsonb_build_object('id',l.id,'club_id',l.club_id,'structure_id',l.structure_id,'course_id',l.course_id,'holes_count',l.holes_count,'review_status',l.review_status,'revision',l.revision,'created_at',l.created_at,'updated_at',l.updated_at,'source_state',(select case when s.id is null or jsonb_typeof(l.source_snapshot->'course') is distinct from 'object' or jsonb_typeof(l.source_snapshot->'holes') is distinct from 'array' then 'unknown' when (l.source_snapshot->'course' @> s.course_value and (l.source_snapshot#>'{course,source_payload}') is not distinct from coalesce(s.source_payload,'null'::jsonb)
        and jsonb_typeof(l.source_snapshot->'holes')='array' and jsonb_array_length(case when jsonb_typeof(l.source_snapshot->'holes')='array' then l.source_snapshot->'holes' else '[]'::jsonb end)=s.hole_count and l.source_snapshot->'holes' @> s.hole_values) then 'matched' else 'changed' end from (select 1) anchor left join course_sources s on s.id=l.course_id)) order by l.id),'[]') from public.admin_catalog_physical_course_links l where l.club_id=p_club_id),
    'configurations',(select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'club_id',c.club_id,'structure_id',c.structure_id,'label',c.label,'holes_count',c.holes_count,'relationship_kind',c.relationship_kind,'parent_configuration_id',c.parent_configuration_id,'parent_configuration_revision',c.parent_configuration_revision,'derivation_rule',c.derivation_rule,'legacy_course_route_id',c.legacy_course_route_id,'legacy_combination_id',c.legacy_combination_id,'registration_kind',c.registration_kind,'review_status',c.review_status,'revision',c.revision,'created_at',c.created_at,'updated_at',c.updated_at,'source_state',case when c.legacy_course_route_id is not null then
        (select case when s.id is null or jsonb_typeof(c.registration_snapshot#>'{source,course}') is distinct from 'object' or jsonb_typeof(c.registration_snapshot#>'{source,holes}') is distinct from 'array' then 'unknown' when (c.registration_snapshot->'source'->'course' @> s.course_value and (c.registration_snapshot->'source'#>'{course,source_payload}') is not distinct from coalesce(s.source_payload,'null'::jsonb)
        and jsonb_typeof(c.registration_snapshot->'source'->'holes')='array' and jsonb_array_length(case when jsonb_typeof(c.registration_snapshot->'source'->'holes')='array' then c.registration_snapshot->'source'->'holes' else '[]'::jsonb end)=s.hole_count and c.registration_snapshot->'source'->'holes' @> s.hole_values) then 'matched' else 'changed' end from (select 1) anchor left join course_sources s on s.id=c.legacy_course_route_id)
        when c.legacy_combination_id is not null then
        (select case when s.id is null or jsonb_typeof(c.registration_snapshot->'source') is distinct from 'object' or jsonb_typeof(c.registration_snapshot->'holes') is distinct from 'array' then 'unknown'
          when c.registration_snapshot->'source' @> s.combination_value and (c.registration_snapshot#>'{source,source_payload}') is not distinct from coalesce(s.source_payload,'null'::jsonb)
            and jsonb_array_length(case when jsonb_typeof(c.registration_snapshot->'holes')='array' then c.registration_snapshot->'holes' else '[]'::jsonb end)=s.hole_count and c.registration_snapshot->'holes' @> s.hole_values then 'matched' else 'changed' end from (select 1) anchor left join combination_sources s on s.id=c.legacy_combination_id)
        else 'unknown' end,'tee_state',case when c.registration_snapshot->'route_tees' is null then 'not_recorded'
        when jsonb_typeof(c.registration_snapshot->'route_tees') is distinct from 'array' then 'unknown'
        when jsonb_array_length(case when jsonb_typeof(c.registration_snapshot->'route_tees')='array' then c.registration_snapshot->'route_tees' else '[]'::jsonb end)=(select count(*) from public.route_tees t where t.route_id=c.legacy_course_route_id)
          and c.registration_snapshot->'route_tees' @> (select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'route_id',t.route_id,'tee_name',t.tee_name,'tee_color',t.tee_color,'gender',t.gender,'holes_count',t.holes_count,'par_total',t.par_total,'course_rating',t.course_rating,'slope_rating',t.slope_rating,'estimated',t.estimated,'source_system',t.source_system,'source_external_id',t.source_external_id,'is_active',t.is_active,'created_at',t.created_at,'updated_at',t.updated_at)),'[]') from public.route_tees t where t.route_id=c.legacy_course_route_id)
          and not exists(select 1 from public.route_tees t where t.route_id=c.legacy_course_route_id and (select b->'source_payload' from jsonb_array_elements(case when jsonb_typeof(c.registration_snapshot->'route_tees')='array' then c.registration_snapshot->'route_tees' else '[]'::jsonb end) b where b->>'id'=t.id::text limit 1) is distinct from coalesce(t.source_payload,'null'::jsonb))
        then 'matched' else 'changed' end) order by c.id),'[]') from public.admin_catalog_playable_configurations c where c.club_id=p_club_id),
    'configuration_holes',(select coalesce(jsonb_agg(jsonb_build_object('id',h.id,'club_id',h.club_id,'structure_id',h.structure_id,'configuration_id',h.configuration_id,'physical_hole_id',h.physical_hole_id,'position',h.position,'occurrence',h.occurrence,'par_mode',h.par_mode,'par_override',h.par_override,'stroke_index',h.stroke_index,'review_status',h.review_status,'revision',h.revision,'legacy_route_hole_id',h.legacy_route_hole_id,'legacy_combination_hole_id',h.legacy_combination_hole_id,'created_at',h.created_at,'updated_at',h.updated_at) order by h.configuration_id,h.position),'[]') from public.admin_catalog_configuration_holes h where h.club_id=p_club_id),
    'components',(select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'club_id',c.club_id,'configuration_id',c.configuration_id,'component_position',c.component_position,'parent_configuration_id',c.parent_configuration_id,'parent_configuration_revision',c.parent_configuration_revision,'physical_course_link_id',c.physical_course_link_id,'physical_course_link_revision',c.physical_course_link_revision,'review_status',c.review_status,'revision',c.revision,'created_at',c.created_at,'updated_at',c.updated_at) order by c.configuration_id,c.component_position),'[]') from public.admin_catalog_configuration_components c where c.club_id=p_club_id),
    'tee_overrides',(select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'configuration_id',t.configuration_id,'configuration_hole_id',t.configuration_hole_id,'route_tee_id',t.route_tee_id,'combination_tee_id',t.combination_tee_id,'par_override',t.par_override,'stroke_index_override',t.stroke_index_override,'review_status',t.review_status,'revision',t.revision,'source_system',case when t.source_system in ('fig','gesgolf','stablr','other','official_club_site') then t.source_system else null end,'created_at',t.created_at,'updated_at',t.updated_at) order by t.id),'[]') from public.admin_catalog_tee_overrides t where exists(select 1 from public.admin_catalog_playable_configurations c where c.id=t.configuration_id and c.club_id=p_club_id)),
    'courses',(select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'club_id',c.club_id,'name',c.name,'holes_count',c.holes_count,'total_par',c.total_par,'is_active',c.is_active,'source_system',case when c.source_system in ('fig','gesgolf','stablr','other','official_club_site') then c.source_system else null end,'created_at',c.created_at,'updated_at',c.updated_at,'tee_matrix',case when c.source_payload->'tee_specific_hole_matrix' is not null and c.source_payload->'tee_specific_hole_matrix'<>'null'::jsonb then jsonb_build_object(
      'present',true,'source',case when c.source_payload#>>'{tee_specific_hole_matrix,source}' in ('fig','gesgolf','stablr','other','official_club_site') then c.source_payload#>>'{tee_specific_hole_matrix,source}' else null end,
      'physical_hole_count',case when jsonb_typeof(c.source_payload#>'{tee_specific_hole_matrix,physical_hole_count}')='number' and (c.source_payload#>'{tee_specific_hole_matrix,physical_hole_count}')::text ~ '^(9|18)$' then ((c.source_payload#>'{tee_specific_hole_matrix,physical_hole_count}')::text)::integer else null end,
      'par_variant',case when jsonb_typeof(c.source_payload#>'{tee_specific_hole_matrix,par_variant}')='number' and (c.source_payload#>'{tee_specific_hole_matrix,par_variant}')::text ~ '^[1-9][0-9]{0,2}$' then ((c.source_payload#>'{tee_specific_hole_matrix,par_variant}')::text)::integer else null end,
      'evidence_status',case when c.source_payload#>>'{tee_specific_hole_matrix,evidence_status}' in ('verified','needs_review') then c.source_payload#>>'{tee_specific_hole_matrix,evidence_status}' else null end,
      'has_unrecognized_entries',jsonb_typeof(c.source_payload#>'{tee_specific_hole_matrix,tees}') is distinct from 'object' or exists(
        select 1 from jsonb_object_keys(case when jsonb_typeof(c.source_payload#>'{tee_specific_hole_matrix,tees}')='object' then c.source_payload#>'{tee_specific_hole_matrix,tees}' else '{}' end) k
        where k not in ('bianco','white','giallo','yellow','blu','blue','rosso','red','arancio','arancione','orange','verde','green','nero','black','viola','purple')),
      'tees',(select coalesce(jsonb_agg(jsonb_build_object('source_key',k,'holes',(select coalesce(jsonb_agg(jsonb_build_object(
        'physical_hole_number',case when jsonb_typeof(h->'physical_hole_number')='number' and (h->'physical_hole_number')::text ~ '^([1-9]|1[0-8])$' then ((h->'physical_hole_number')::text)::integer else null end,
        'par',case when jsonb_typeof(h->'par')='number' and (h->'par')::text ~ '^[3-6]$' then ((h->'par')::text)::integer else null end,
        'stroke_indexes',(select coalesce(jsonb_agg(case when jsonb_typeof(si)='number' and si::text ~ '^([1-9]|1[0-8])$' then (si::text)::integer else null end order by ord),'[]')
          from jsonb_array_elements(case when jsonb_typeof(h->'stroke_indexes')='array' then h->'stroke_indexes' else '[]'::jsonb end) with ordinality x(si,ord) where ord<=2)
        ) order by ord),'[]') from jsonb_array_elements(case when jsonb_typeof(c.source_payload#>array['tee_specific_hole_matrix','tees',k,'holes'])='array' then c.source_payload#>array['tee_specific_hole_matrix','tees',k,'holes'] else '[]'::jsonb end) with ordinality x(h,ord)
        where ord<=18)) order by k),'[]')
        from unnest(array['bianco','white','giallo','yellow','blu','blue','rosso','red','arancio','arancione','orange','verde','green','nero','black','viola','purple']) k
        where (case when jsonb_typeof(c.source_payload#>'{tee_specific_hole_matrix,tees}')='object' then c.source_payload#>'{tee_specific_hole_matrix,tees}' else '{}' end) ? k)
    ) else null end) order by c.id),'[]') from public.course_routes c where c.club_id=p_club_id),
    'course_holes',(select coalesce(jsonb_agg(jsonb_build_object('id',h.id,'route_id',h.route_id,'physical_hole_number',h.physical_hole_number,'par',h.par,'stroke_index',h.stroke_index) order by h.route_id,h.physical_hole_number,h.id),'[]') from public.route_holes h where exists(select 1 from public.course_routes c where c.id=h.route_id and c.club_id=p_club_id)),
    'combinations',(select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'club_id',c.club_id,'name',c.name,'holes_count',c.holes_count,'total_par',c.total_par,'front_route_id',c.front_route_id,'back_route_id',c.back_route_id,'is_active',c.is_active,'source_system',case when c.source_system in ('fig','gesgolf','stablr','other','official_club_site') then c.source_system else null end,'created_at',c.created_at,'updated_at',c.updated_at) order by c.id),'[]') from public.route_combinations c where c.club_id=p_club_id),
    'combination_holes',(select coalesce(jsonb_agg(jsonb_build_object('id',h.id,'route_combination_id',h.route_combination_id,'round_hole_number',h.round_hole_number,'route_id',h.route_id,'route_position',h.route_position,'physical_hole_number',h.physical_hole_number,'par',h.par,'stroke_index',h.stroke_index) order by h.route_combination_id,h.round_hole_number,h.id),'[]') from public.route_combination_holes h where exists(select 1 from public.route_combinations c where c.id=h.route_combination_id and c.club_id=p_club_id)),
    'route_tees',(select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'route_id',t.route_id,'tee_name',t.tee_name,'tee_color',t.tee_color,'gender',t.gender,'holes_count',t.holes_count,'par_total',t.par_total,'course_rating',t.course_rating,'slope_rating',t.slope_rating,'is_active',t.is_active,'source_system',case when t.source_system in ('fig','gesgolf','stablr','other','official_club_site') then t.source_system else null end,'created_at',t.created_at,'updated_at',t.updated_at,'payload_present',t.source_payload is not null and t.source_payload<>'null'::jsonb) order by t.id),'[]') from public.route_tees t where exists(select 1 from public.course_routes c where c.id=t.route_id and c.club_id=p_club_id)),
    'combination_tees',(select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'route_combination_id',t.route_combination_id,'tee_name',t.tee_name,'tee_color',t.tee_color,'gender',t.gender,'holes_count',t.holes_count,'par_total',t.par_total,'course_rating',t.course_rating,'slope_rating',t.slope_rating,'is_active',t.is_active,'source_system',case when t.source_system in ('fig','gesgolf','stablr','other','official_club_site') then t.source_system else null end,'created_at',t.created_at,'updated_at',t.updated_at,'payload_present',t.source_payload is not null and t.source_payload<>'null'::jsonb) order by t.id),'[]') from public.combination_tees t where exists(select 1 from public.route_combinations c where c.id=t.route_combination_id and c.club_id=p_club_id)),
    'drafts',(select coalesce(jsonb_agg(jsonb_build_object(
      'draft_id',d.draft_id,'entity_type',d.entity_type,'live_entity_id',d.live_entity_id,
      'workflow_status',d.workflow_status,'revision',d.revision,'created_at',d.created_at,'updated_at',d.updated_at,
      'is_owner',d.created_by=auth.uid(),'author',case when d.created_by=auth.uid() then 'current_admin' else 'other_admin' end,
      'has_changes',d.base_snapshot is null or d.snapshot_value is null or d.snapshot_value is distinct from d.base_value,
      'base_status',case when d.base_snapshot is null or d.base_value is null or d.current_value is null then 'unknown'
        when d.base_value is distinct from d.current_value or d.latest_version_id is distinct from d.base_version_id
          or (d.base_live_updated_at is not null and d.live_updated_at is not null and d.base_live_updated_at<>d.live_updated_at)
        then 'changed' else 'checked_fields' end
    ) order by d.updated_at desc,d.draft_id),'[]') from draft_values d)
  ) into result;
  return result;
end $$;

revoke all on function public.admin_catalog_data_origin(uuid) from public,anon,authenticated,service_role;
grant execute on function public.admin_catalog_data_origin(uuid) to authenticated;
notify pgrst,'reload schema';
commit;
